"""
Don't understand the purpose of these column, confuse me more
than give insights, put them aside for now. Ambiguous values.

value
amount:
"""

R_INIT_COL_NAMES = (
    "arrival_ts",
    "country_code",
    "data.*",
    "user_meta.*",
)

R_MID_COL_NAMES = (
    "arrival_ts",
    "country_code",
    "amount",
    "android_id",
    "attempt_num",
    "category",
    "client_ts",
    "connection_type",
    "jailbroken",
    "length",
    "limited_ad_tracking",
    "manufacturer",
    "platform",
    "score",
    "session_id",
    "session_num",
    "user_id",
    "v",
    "value",
    "cohort_month",
    "cohort_week",
    "first_build",
    "install_hour",
    "install_ts",
    "is_converting",
    "is_paying",
    "origin",
    "pay_ft",
    "revenue.*",
)

R_FINAL_COL_NAMES = (
    "arrival_ts",
    "country_code",
    "amount",
    "android_id",
    "attempt_num",
    "category",
    "client_ts",
    "connection_type",
    "jailbroken",
    "length",
    "limited_ad_tracking",
    "manufacturer",
    "platform",
    "score",
    "session_id",
    "session_num",
    "user_id",
    "v",
    "value",
    "cohort_month",
    "cohort_week",
    "first_build",
    "install_hour",
    "install_ts",
    "is_converting",
    "is_paying",
    "origin",
    "pay_ft",
    "AUD",
    "CAD",
    "CZK",
    "EUR",
    "GBP",
    "HUF",
    "NOK",
    "PHP",
    "RUB",
    "SEK",
    "USD",
    "ZAR",
)
