version: '3.0'
services:
        # PostgreSQL 11.5 (Debian 11.5-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
        postgres-db:
                container_name: "data-engine_postgres"
                restart: "always"
                image: postgres
                env_file:
                  - ./config/postgres.env
                volumes:
                  - ./postgres_volume:/var/lib/postgresql/data/
                  - ./services/postgres/:/docker-entrypoint-initdb.d/
                ports:
                  - 5432:5432

        # metabase
        metabase:
                container_name: "data-engine_metabase"
                restart: "always"
                image: metabase/metabase
                environment:
                  MB_DB_HOST: postgres-db
                env_file:
                  - ./config/metabase_database.env
                ports:
                  - 3000:3000
                depends_on:
                  - postgres-db
        # MinIO simulate S3
        minio:
                image: minio/minio
                ports:
                        - '9000:9000'
                volumes:
                        - ./data/.minio/data:/export
                        - ./data/.minio/config:/root/.minio
                environment:
                        - 'MINIO_ACCESS_KEY=libertapoweruser'
                        - 'MINIO_SECRET_KEY=libertapoweruserpassword'
                command: server /export
        # create a bucket to run locally
        createbuckets:
                image: minio/mc
                links:
                        - minio
                restart: on-failure
                entrypoint: >
                      /bin/sh -c "
                        echo Waiting for minio service to start...;
                        while ! nc -z minio 9000;
                        do
                          sleep 1;
                        done;
                        echo Connected!;
                        mc config host add myminio http://minio:9000 libertapoweruser libertapoweruserpassword;
                        /usr/bin/mc mb myminio/rawevents;
                        /usr/bin/mc policy download myminio/rawevents;
                        /usr/bin/mc policy upload myminio/rawevents;
                        exit 0;
                      "
networks:
  liberta-app-default:
